### ISSUE TITLE
Remove inflection, use custom conversion for casing

### ISSUE THREAD

**Issue by tonythomas01** [3YOURMIND/drf-payload-customizer#6]
@dodekeract found some edge-cases where inflection can mess things up. For eg, with `UUID-123` which surprisingly got converted to `UUID123`. 

Let us use a custom regex based approach here. Might be expensive, but better in the long run.

**Comment by FlorianWendelborn** [comment]
@tonythomas01 If you mean expensive (as in CPU time), take a look at the [`inflection` source code](https://github.com/jpvanhal/inflection/blob/2ea54f615924c5cfc967d50cc179eacf0b269c08/inflection.py#L394-L413).

**Comment by tonythomas01** [comment]
Jeez. this is the same. I lean back.

**Comment by tonythomas01** [comment]
Already fixed by https://github.com/3YOURMIND/drf-payload-customizer/pull/7
